### PR TITLE
Add subreddit-about method to retrieve information about subreddit

### PR DESCRIPTION
**Pull request by sharms**

### CODE REVIEW

**Comment by ThatGuyHughesy** [comment]
Hey @sharms cheers for the pull request!

Code looks good, just a few housekeeping rules 😛 Can you have a look at the [CONTRIBUTING.md](https://github.com/ThatGuyHughesy/creddit/blob/master/CONTRIBUTING.md) pull request checklist?

**Comment by sharms** [comment]
I have squashed the commits and added a readme update to show the method.

**Comment by ThatGuyHughesy** [comment]
I think subreddit-about should be a separate "section" in the README since the other methods are all related to retrieving posts, similar to how subreddit-search is done, something like this:

*Retrieve information about subreddit*

**subreddit:** Name of subreddit (Eg: "programming", "funny", "pics" etc...)  

```clojure
(creddit/subreddit-about creddit-client subreddit)
```

Can you also add a quick test for subreddit-about?

**Comment by sharms** [comment]
Hi, I have updated with a short test and entry in the readme, how does this look?

**Comment by ThatGuyHughesy** [comment]
Hey sharms, thanks for the update!

Hate to do this but just two points.

1) Can you update the README and move the about method example to be under its details like this:

*Retrieve information about subreddit*

**subreddit:** Name of subreddit (Eg: "programming", "funny", "pics" etc...)  

```clojure
(creddit/subreddit-about creddit-client subreddit)
```

2) Squash your commits

Then I'll merge straightaway I swear! 😝

**Comment by sharms** [comment]
Sure that was a good catch, I didn't notice I left the subreddit-about stuck in the old stanza thanks!

**Comment by ThatGuyHughesy** [comment]
A good chunk of my day is spent staring at merge requests so I've become pretty good a spotting things 😆 

All merged! Thanks again for the contributing and sorry for being so particular about everything 😝

**Pull request merged**
